name: First workflow

on: workflow_dispatch

jobs:
  #job.id job의 이름 임의의 이름
  first-jobs:
    #

    runs-on: ubuntu-latest

    steps:

      - name: Print Greeting

        run: echo "Hello World!"

 

      - name: Print Goodbye

        run: echo " Done ! Bye"